version: "3"
services: 
  server:
   build: 
     context: .
     dockerfile: ./applications/server/Dockerfile
   command: "yarn run server:start"
   restart: always
   volumes: 
    - .:/application/:rw
   ports: 
    - "1337:1337"
    - "9226:9226"
   depends_on: 
    - postgres
  postgres:
    image: postgres:latest
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_USER=SYSDBA
      - POSTGRES_PASSWORD=masterkey
      - POSTGRES_DB=eprocurement
volumes: 
  static: {}